name: OpenShift CI/CD Workflow

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  GHCR_USERNAME: ${{ secrets.GITHUB_ACTOR }}
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GHCR_IMAGE_NAME: "ghcr.io/hackleberry-group/test-service-bj"
  DOCKER_IMAGE_TAG: "latest"
  OPENSHIFT_NAMESPACE: "delta-dev"
  APP_NAME: "test-service-bj-ghcr"
  APP_PORT: "1030"
  IMAGE_TAGS: "latest"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  openshift-ci-cd:
    name: Build, Push, and Deploy to OpenShift
    runs-on: ubuntu-20.04

    steps:
      - name: Check for required secrets
        uses: actions/github-script@v6
        with:
          script: |
            const secrets = {
              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`
            };

            const missingSecrets = Object.entries(secrets).filter(([key, value]) => !value);
            if (missingSecrets.length > 0) {
              core.setFailed(`The following secrets are missing: ${missingSecrets.map(([key]) => key).join(', ')}`);
            }

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ env.GHCR_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker push ${{ env.GHCR_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4.10

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Set Registry Path as Environment Variable
        run: echo "REGISTRY_PATH=${{ env.GHCR_IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Deploy to OpenShift from GHCR
        id: deploy-and-expose
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.APP_NAME }}
          image: ${{ env.REGISTRY_PATH }}:${{ env.DOCKER_IMAGE_TAG }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Print application URL
        run: |
          echo "Your application is deployed and accessible at:"
          oc get route ${{ env.APP_NAME }} -o jsonpath='{.spec.host}'